### ISSUE TITLE
Implement deletion of verses

### ISSUE THREAD

**Issue by isaacjwilliams** [aiwilliams/verses#2]

**Comment by aiwilliams** [comment]
I was thinking about the table of verses. I think we should allow for entering "James", and that will be 1 row in the table. This would fetch the verses and store them, and then when I'm "reciting", I will be working on 1 verse at a time. I don't think that deleting a verse should ever remove the record of my effort to memorize, either, once we have such a record :grin:

**Comment by isaacjwilliams** [comment]
So what would happen if they want to stop memorizing a passage? What will keep the table view from getting ridiculously crowded?

When you say "I think we should allow for entering 'James', and that will be 1 row in the table", what do you mean? What if I want to memorize James 1:1? Will the table row still just be "James"?
