### ISSUE TITLE
Disable help button immediately if using free helps

### ISSUE THREAD

**Issue by isaacjwilliams** [aiwilliams/verses#32]

**Comment by aiwilliams** [comment]
I wonder if we were too hasty here... perhaps what we mean is to disable the Help button if we are showing the advanced help already?

It is not clear to me what is happening here:

``` swift
        if Int(activeVerse.views!) < 5 {
            helpButton.enabled = false
            advancedHelpLabel.alpha = 1
        }

        helpButton.enabled = false
```

This leads me to think the button will never be enabled.

Also, the value of `5` is a bit magical. Perhaps an Enum-like thing would give constant names that indicate the significance of `5`?

**Comment by isaacjwilliams** [comment]
@aiwilliams You were correct when you thought that the button will never be enabled. I fixed that problem in the commit subsequent to this one. :grin:

I think that in the latest version of the code the intent is clear enough without an enum. Maybe you can take another look?
