### ISSUE TITLE
Overshot passages should default to last verse of passage

### ISSUE THREAD

**Issue by aiwilliams** [aiwilliams/verses#54]

**Comment by aiwilliams** [comment]
18 does not exist. Maybe we could tell the user "that book ends at verse 17"

**Comment by isaacjwilliams** [comment]
@aiwilliams Recently you said that ought not give warnings but rather should display an empty preview; does that statement apply to this issue?

**Comment by aiwilliams** [comment]
Hmmm, good question! I think I would just choose the last verse number of the chapter if they've gone beyond the bounds of the chapter.
